### ISSUE TITLE
Error receiving email

### ISSUE THREAD

**Issue by anton-johansson** [deitch/smtp-tester#25]
I'm getting the following when I'm receiving an email:

```
TypeError: Cannot set property errored of # which has only a getter
    at new MessageSplitter (/home/anton/projects/my-project/node_modules/mailsplit/lib/message-splitter.js:28:22)
    at new MailParser (/home/anton/projects/my-project/node_modules/mailparser/lib/mail-parser.js:132:25)
    at module.exports (/home/anton/projects/my-project/node_modules/mailparser/lib/simple-parser.js:25:18)
    at buildEmail (/home/anton/projects/my-project/node_modules/smtp-tester/lib/index.js:114:10)
    at PassThrough. (/home/anton/projects/my-project/node_modules/smtp-tester/lib/index.js:162:9)
    at PassThrough.emit (node:events:527:28)
    at PassThrough.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I've set up the server simply with this:

```js
const server = ms.init(3025);
server.bind(data => {
    console.log("receive", data);
});
```

**Comment by anton-johansson** [comment]
I'm fairly sure that this is because I'm running on NodeJS 18. I see that `nodemailer` made a change regarding this:

https://github.com/nodemailer/mailparser/commit/88c26ca389f7f6f0ccafac14f971ee37f7eff1d6

**Comment by anton-johansson** [comment]
See #27.
